import test_type_cim_v1_activity_ensemble
import test_type_cim_v1_activity_numerical_experiment
import test_type_cim_v1_activity_simulation_run
import test_type_cim_v1_data_data_object
import test_type_cim_v1_grids_gridspec
import test_type_cim_v1_misc_document_set
import test_type_cim_v1_quality_cim_quality
import test_type_cim_v1_shared_platform
import test_type_cim_v1_software_model_component
import test_type_cim_v1_software_statistical_model_component


MODULES = (
    test_type_cim_v1_activity_ensemble,
    test_type_cim_v1_activity_numerical_experiment,
    test_type_cim_v1_activity_simulation_run,
    test_type_cim_v1_data_data_object,
    test_type_cim_v1_grids_gridspec,
    test_type_cim_v1_misc_document_set,    
    test_type_cim_v1_quality_cim_quality,
    test_type_cim_v1_shared_platform,
    test_type_cim_v1_software_model_component,
    test_type_cim_v1_software_statistical_model_component,
)