"""
A set of cim related unit tests.
"""

# Module imports.
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_activity_ensemble import TestDecodeEnsemble
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_activity_ensemble_1 import TestDecodeEnsemble_1
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_activity_numerical_experiment import TestDecodeNumericalExperiment
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_activity_simulation_run import TestDecodeSimulationRun
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_data_data_object import TestDecodeDataObject
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_grids_gridspec import TestDecodeGridSpec
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_quality_cim_quality import TestDecodeCimQuality
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_shared_platform import TestDecodePlatform
from pyesdoc_test.ontologies.cim.v1_5.test_decoding_software_model_component import TestDecodeModelComponent


