# -*- coding: utf-8 -*-

"""
.. module:: cim.v2.constraints.py

   :license: GPL / CeCILL
   :platform: Unix, Windows
   :synopsis: The set of constraints over the cim.v2.

.. moduleauthor:: Earth System Documentation (ES-DOC) <dev@es-doc.org>
.. note:: Code generated using the esdoc-mp framework.

"""
import datetime
import uuid

import typeset_for_activity_package as activity
import typeset_for_data_package as data
import typeset_for_designing_package as designing
import typeset_for_drs_package as drs
import typeset_for_platform_package as platform
import typeset_for_science_package as science
import typeset_for_shared_package as shared
import typeset_for_software_package as software



# Map of ontology types to type constraints.
CONSTRAINTS = {
    activity.Activity: (
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    activity.AxisMember: (
        ('description', 'cardinality', '1.1'),
        ('description', 'type', unicode),
        ('extra_detail', 'cardinality', '0.1'),
        ('extra_detail', 'type', unicode),
        ('index', 'cardinality', '1.1'),
        ('index', 'type', int),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', float),
    ),

    activity.Conformance: (
        ('canonical_name', 'cardinality', '0.0'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '1.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.0'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.0'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('target_requirement', 'cardinality', '1.1'),
        ('target_requirement', 'type', designing.NumericalRequirement),
    ),

    activity.Ensemble: (
        ('canonical_name', 'cardinality', '0.0'),
        ('canonical_name', 'type', unicode),
        ('common_conformances', 'cardinality', '0.N'),
        ('common_conformances', 'type', activity.Conformance),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('documentation', 'cardinality', '0.N'),
        ('documentation', 'type', shared.OnlineResource),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('has_ensemble_axes', 'cardinality', '0.N'),
        ('has_ensemble_axes', 'type', activity.EnsembleAxis),
        ('keywords', 'cardinality', '0.0'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('members', 'cardinality', '1.N'),
        ('members', 'type', activity.EnsembleMember),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('part_of', 'cardinality', '0.N'),
        ('part_of', 'type', activity.UberEnsemble),
        ('rationale', 'cardinality', '0.0'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('supported', 'cardinality', '1.N'),
        ('supported', 'type', designing.NumericalExperiment),
    ),

    activity.EnsembleAxis: (
        ('extra_detail', 'cardinality', '1.1'),
        ('extra_detail', 'type', unicode),
        ('member', 'cardinality', '1.N'),
        ('member', 'type', activity.AxisMember),
        ('short_identifier', 'cardinality', '1.1'),
        ('short_identifier', 'type', unicode),
        ('target_requirement', 'cardinality', '1.1'),
        ('target_requirement', 'type', designing.NumericalRequirement),
    ),

    activity.EnsembleMember: (
        ('errata', 'cardinality', '0.1'),
        ('errata', 'type', shared.OnlineResource),
        ('had_performance', 'cardinality', '0.1'),
        ('had_performance', 'type', platform.Performance),
        ('ran_on', 'cardinality', '0.1'),
        ('ran_on', 'type', platform.Machine),
        ('simulation', 'cardinality', '1.1'),
        ('simulation', 'type', data.Simulation),
        ('variant_id', 'cardinality', '1.1'),
        ('variant_id', 'type', unicode),
    ),

    activity.ParentSimulation: (
        ('branch_time_in_child', 'cardinality', '0.1'),
        ('branch_time_in_child', 'type', shared.DateTime),
        ('branch_time_in_parent', 'cardinality', '0.1'),
        ('branch_time_in_parent', 'type', shared.DateTime),
        ('parent', 'cardinality', '1.1'),
        ('parent', 'type', data.Simulation),
    ),

    activity.UberEnsemble: (
        ('canonical_name', 'cardinality', '0.0'),
        ('canonical_name', 'type', unicode),
        ('child_ensembles', 'cardinality', '1.N'),
        ('child_ensembles', 'type', activity.Ensemble),
        ('common_conformances', 'cardinality', '0.0'),
        ('common_conformances', 'type', activity.Conformance),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('documentation', 'cardinality', '0.N'),
        ('documentation', 'type', shared.OnlineResource),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('has_ensemble_axes', 'cardinality', '1.N'),
        ('has_ensemble_axes', 'type', activity.EnsembleAxis),
        ('keywords', 'cardinality', '0.0'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('members', 'cardinality', '0.0'),
        ('members', 'type', activity.EnsembleMember),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('part_of', 'cardinality', '0.N'),
        ('part_of', 'type', activity.UberEnsemble),
        ('rationale', 'cardinality', '0.0'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('supported', 'cardinality', '1.N'),
        ('supported', 'type', designing.NumericalExperiment),
    ),

    data.Dataset: (
        ('availability', 'cardinality', '0.N'),
        ('availability', 'type', shared.OnlineResource),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('drs_datasets', 'cardinality', '0.N'),
        ('drs_datasets', 'type', drs.DrsPublicationDataset),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('produced_by', 'cardinality', '0.1'),
        ('produced_by', 'type', data.Simulation),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('related_to_dataset', 'cardinality', '0.N'),
        ('related_to_dataset', 'type', shared.OnlineResource),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    data.Downscaling: (
        ('calendar', 'cardinality', '0.1'),
        ('calendar', 'type', shared.Calendar),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('downscaled_from', 'cardinality', '1.1'),
        ('downscaled_from', 'type', data.Simulation),
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', shared.TimePeriod),
        ('ensemble_identifier', 'cardinality', '1.1'),
        ('ensemble_identifier', 'type', unicode),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('parent_simulation', 'cardinality', '0.0'),
        ('parent_simulation', 'type', activity.ParentSimulation),
        ('part_of_project', 'cardinality', '1.N'),
        ('part_of_project', 'type', designing.Project),
        ('primary_ensemble', 'cardinality', '0.1'),
        ('primary_ensemble', 'type', activity.Ensemble),
        ('ran_for_experiments', 'cardinality', '1.N'),
        ('ran_for_experiments', 'type', designing.NumericalExperiment),
        ('rationale', 'cardinality', '0.0'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('used', 'cardinality', '1.1'),
        ('used', 'type', science.Model),
    ),

    data.Simulation: (
        ('calendar', 'cardinality', '0.1'),
        ('calendar', 'type', shared.Calendar),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', shared.TimePeriod),
        ('ensemble_identifier', 'cardinality', '1.1'),
        ('ensemble_identifier', 'type', unicode),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('parent_simulation', 'cardinality', '0.1'),
        ('parent_simulation', 'type', activity.ParentSimulation),
        ('part_of_project', 'cardinality', '1.N'),
        ('part_of_project', 'type', designing.Project),
        ('primary_ensemble', 'cardinality', '0.1'),
        ('primary_ensemble', 'type', activity.Ensemble),
        ('ran_for_experiments', 'cardinality', '1.N'),
        ('ran_for_experiments', 'type', designing.NumericalExperiment),
        ('rationale', 'cardinality', '0.0'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('used', 'cardinality', '1.1'),
        ('used', 'type', science.Model),
    ),

    data.VariableCollection: (
        ('collection_name', 'cardinality', '0.1'),
        ('collection_name', 'type', unicode),
        ('variables', 'cardinality', '1.N'),
        ('variables', 'type', unicode),
    ),

    designing.DomainProperties: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('required_extent', 'cardinality', '0.1'),
        ('required_extent', 'type', science.Extent),
        ('required_resolution', 'cardinality', '0.1'),
        ('required_resolution', 'type', science.Resolution),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.EnsembleRequirement: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('ensemble_member', 'cardinality', '0.N'),
        ('ensemble_member', 'type', designing.NumericalRequirement),
        ('ensemble_type', 'cardinality', '1.1'),
        ('ensemble_type', 'type', unicode),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('minimum_size', 'cardinality', '1.1'),
        ('minimum_size', 'type', int),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.ForcingConstraint: (
        ('additional_constraint', 'cardinality', '0.1'),
        ('additional_constraint', 'type', unicode),
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('category', 'cardinality', '0.1'),
        ('category', 'type', unicode),
        ('code', 'cardinality', '0.1'),
        ('code', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('data_link', 'cardinality', '0.1'),
        ('data_link', 'type', shared.OnlineResource),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('forcing_type', 'cardinality', '1.1'),
        ('forcing_type', 'type', unicode),
        ('group', 'cardinality', '0.1'),
        ('group', 'type', unicode),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('origin', 'cardinality', '0.1'),
        ('origin', 'type', shared.Reference),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.MultiEnsemble: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('ensemble_axis', 'cardinality', '1.N'),
        ('ensemble_axis', 'type', designing.EnsembleRequirement),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.MultiTimeEnsemble: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('ensemble_members', 'cardinality', '1.1'),
        ('ensemble_members', 'type', shared.DatetimeSet),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.NumericalExperiment: (
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '1.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('related_experiments', 'cardinality', '0.N'),
        ('related_experiments', 'type', designing.NumericalExperiment),
        ('requirements', 'cardinality', '0.N'),
        ('requirements', 'type', designing.NumericalRequirement),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.NumericalRequirement: (
        ('additional_requirements', 'cardinality', '0.N'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
    ),

    designing.OutputTemporalRequirement: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('continuous_subset', 'cardinality', '0.N'),
        ('continuous_subset', 'type', shared.TimePeriod),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('sliced_subset', 'cardinality', '0.1'),
        ('sliced_subset', 'type', shared.TimesliceList),
        ('throughout', 'cardinality', '1.1'),
        ('throughout', 'type', bool),
    ),

    designing.Project: (
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '1.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('previous_projects', 'cardinality', '0.N'),
        ('previous_projects', 'type', designing.Project),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('requires_experiments', 'cardinality', '0.N'),
        ('requires_experiments', 'type', designing.NumericalExperiment),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('sub_projects', 'cardinality', '0.N'),
        ('sub_projects', 'type', designing.Project),
    ),

    designing.SimulationPlan: (
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '1.1'),
        ('duration', 'type', shared.TimePeriod),
        ('expected_model', 'cardinality', '1.1'),
        ('expected_model', 'type', science.Model),
        ('expected_performance_sypd', 'cardinality', '0.1'),
        ('expected_performance_sypd', 'type', float),
        ('expected_platform', 'cardinality', '0.1'),
        ('expected_platform', 'type', platform.Machine),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('will_support_experiments', 'cardinality', '1.N'),
        ('will_support_experiments', 'type', designing.NumericalExperiment),
    ),

    designing.TemporalConstraint: (
        ('additional_requirements', 'cardinality', '0.0'),
        ('additional_requirements', 'type', designing.NumericalRequirement),
        ('canonical_name', 'cardinality', '0.1'),
        ('canonical_name', 'type', unicode),
        ('conformance_is_requested', 'cardinality', '1.1'),
        ('conformance_is_requested', 'type', bool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('duration', 'cardinality', '0.0'),
        ('duration', 'type', shared.TimePeriod),
        ('keywords', 'cardinality', '0.N'),
        ('keywords', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('rationale', 'cardinality', '0.1'),
        ('rationale', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('required_calendar', 'cardinality', '0.1'),
        ('required_calendar', 'type', shared.Calendar),
        ('required_duration', 'cardinality', '0.1'),
        ('required_duration', 'type', shared.TimePeriod),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.Responsibility),
        ('start_date', 'cardinality', '0.1'),
        ('start_date', 'type', shared.DateTime),
        ('start_flexibility', 'cardinality', '0.1'),
        ('start_flexibility', 'type', shared.TimePeriod),
    ),

    drs.DrsAtomicDataset: (
        ('activity', 'cardinality', '1.1'),
        ('activity', 'type', unicode),
        ('ensemble_member', 'cardinality', '1.1'),
        ('ensemble_member', 'type', drs.DrsEnsembleIdentifier),
        ('experiment', 'cardinality', '1.1'),
        ('experiment', 'type', unicode),
        ('frequency', 'cardinality', '1.1'),
        ('frequency', 'type', unicode),
        ('geographical_constraint', 'cardinality', '0.1'),
        ('geographical_constraint', 'type', drs.DrsGeographicalIndicator),
        ('institute', 'cardinality', '1.1'),
        ('institute', 'type', unicode),
        ('mip_table', 'cardinality', '1.1'),
        ('mip_table', 'type', unicode),
        ('model', 'cardinality', '1.1'),
        ('model', 'type', unicode),
        ('product', 'cardinality', '1.1'),
        ('product', 'type', unicode),
        ('realm', 'cardinality', '1.1'),
        ('realm', 'type', unicode),
        ('temporal_constraint', 'cardinality', '0.1'),
        ('temporal_constraint', 'type', drs.DrsTemporalIdentifier),
        ('variable_name', 'cardinality', '1.1'),
        ('variable_name', 'type', unicode),
        ('version_number', 'cardinality', '1.1'),
        ('version_number', 'type', int),
    ),

    drs.DrsEnsembleIdentifier: (
        ('initialisation_method_number', 'cardinality', '1.1'),
        ('initialisation_method_number', 'type', int),
        ('perturbation_number', 'cardinality', '1.1'),
        ('perturbation_number', 'type', int),
        ('realisation_number', 'cardinality', '1.1'),
        ('realisation_number', 'type', int),
    ),

    drs.DrsGeographicalIndicator: (
        ('bounding_box', 'cardinality', '0.1'),
        ('bounding_box', 'type', unicode),
        ('operator', 'cardinality', '0.1'),
        ('operator', 'type', unicode),
        ('spatial_domain', 'cardinality', '0.1'),
        ('spatial_domain', 'type', unicode),
    ),

    drs.DrsPublicationDataset: (
        ('activity', 'cardinality', '1.1'),
        ('activity', 'type', unicode),
        ('experiment', 'cardinality', '1.1'),
        ('experiment', 'type', unicode),
        ('frequency', 'cardinality', '0.1'),
        ('frequency', 'type', unicode),
        ('institute', 'cardinality', '1.1'),
        ('institute', 'type', unicode),
        ('model', 'cardinality', '1.1'),
        ('model', 'type', unicode),
        ('product', 'cardinality', '1.1'),
        ('product', 'type', unicode),
        ('realm', 'cardinality', '0.1'),
        ('realm', 'type', unicode),
        ('version_number', 'cardinality', '0.1'),
        ('version_number', 'type', int),
    ),

    drs.DrsTemporalIdentifier: (
        ('end', 'cardinality', '0.1'),
        ('end', 'type', unicode),
        ('start', 'cardinality', '1.1'),
        ('start', 'type', unicode),
        ('suffix', 'cardinality', '0.1'),
        ('suffix', 'type', unicode),
    ),

    platform.ComponentPerformance: (
        ('component', 'cardinality', '0.1'),
        ('component', 'type', software.SoftwareComponent),
        ('component_name', 'cardinality', '1.1'),
        ('component_name', 'type', unicode),
        ('cores_used', 'cardinality', '0.1'),
        ('cores_used', 'type', int),
        ('nodes_used', 'cardinality', '0.1'),
        ('nodes_used', 'type', int),
        ('speed', 'cardinality', '1.1'),
        ('speed', 'type', float),
    ),

    platform.ComputePool: (
        ('accelerator_type', 'cardinality', '0.1'),
        ('accelerator_type', 'type', unicode),
        ('accelerators_per_node', 'cardinality', '0.1'),
        ('accelerators_per_node', 'type', int),
        ('compute_cores_per_node', 'cardinality', '0.1'),
        ('compute_cores_per_node', 'type', int),
        ('cpu_type', 'cardinality', '0.1'),
        ('cpu_type', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('interconnect', 'cardinality', '0.1'),
        ('interconnect', 'type', unicode),
        ('memory_per_node', 'cardinality', '0.1'),
        ('memory_per_node', 'type', platform.StorageVolume),
        ('model_number', 'cardinality', '0.1'),
        ('model_number', 'type', unicode),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('number_of_nodes', 'cardinality', '0.1'),
        ('number_of_nodes', 'type', int),
        ('operating_system', 'cardinality', '0.1'),
        ('operating_system', 'type', unicode),
    ),

    platform.Machine: (
        ('compute_pools', 'cardinality', '1.N'),
        ('compute_pools', 'type', platform.ComputePool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('institution', 'cardinality', '1.1'),
        ('institution', 'type', shared.Party),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('model_number', 'cardinality', '0.1'),
        ('model_number', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('online_documentation', 'cardinality', '0.N'),
        ('online_documentation', 'type', shared.OnlineResource),
        ('partition', 'cardinality', '0.N'),
        ('partition', 'type', platform.Partition),
        ('storage_pools', 'cardinality', '0.N'),
        ('storage_pools', 'type', platform.StoragePool),
        ('vendor', 'cardinality', '0.1'),
        ('vendor', 'type', shared.Party),
        ('when_used', 'cardinality', '0.1'),
        ('when_used', 'type', shared.TimePeriod),
    ),

    platform.Partition: (
        ('compute_pools', 'cardinality', '1.N'),
        ('compute_pools', 'type', platform.ComputePool),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('institution', 'cardinality', '1.1'),
        ('institution', 'type', shared.Party),
        ('model_number', 'cardinality', '0.1'),
        ('model_number', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('online_documentation', 'cardinality', '0.N'),
        ('online_documentation', 'type', shared.OnlineResource),
        ('partition', 'cardinality', '0.N'),
        ('partition', 'type', platform.Partition),
        ('storage_pools', 'cardinality', '0.N'),
        ('storage_pools', 'type', platform.StoragePool),
        ('vendor', 'cardinality', '0.1'),
        ('vendor', 'type', shared.Party),
        ('when_used', 'cardinality', '0.1'),
        ('when_used', 'type', shared.TimePeriod),
    ),

    platform.Performance: (
        ('asypd', 'cardinality', '0.1'),
        ('asypd', 'type', float),
        ('chsy', 'cardinality', '0.1'),
        ('chsy', 'type', float),
        ('compiler', 'cardinality', '0.1'),
        ('compiler', 'type', unicode),
        ('coupler_load', 'cardinality', '0.1'),
        ('coupler_load', 'type', float),
        ('io_load', 'cardinality', '0.1'),
        ('io_load', 'type', float),
        ('load_imbalance', 'cardinality', '0.1'),
        ('load_imbalance', 'type', float),
        ('memory_bloat', 'cardinality', '0.1'),
        ('memory_bloat', 'type', float),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('model', 'cardinality', '1.1'),
        ('model', 'type', science.Model),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('platform', 'cardinality', '1.1'),
        ('platform', 'type', platform.Machine),
        ('subcomponent_performance', 'cardinality', '0.1'),
        ('subcomponent_performance', 'type', platform.ComponentPerformance),
        ('sypd', 'cardinality', '0.1'),
        ('sypd', 'type', float),
        ('total_nodes_used', 'cardinality', '0.1'),
        ('total_nodes_used', 'type', int),
    ),

    platform.StoragePool: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('vendor', 'cardinality', '0.1'),
        ('vendor', 'type', shared.Party),
        ('volume_available', 'cardinality', '1.1'),
        ('volume_available', 'type', platform.StorageVolume),
    ),

    platform.StorageVolume: (
        ('units', 'cardinality', '1.1'),
        ('units', 'type', unicode),
        ('volume', 'cardinality', '1.1'),
        ('volume', 'type', int),
    ),

    science.Algorithm: (
        ('context', 'cardinality', '1.1'),
        ('context', 'type', unicode),
        ('diagnostic_variables', 'cardinality', '0.1'),
        ('diagnostic_variables', 'type', data.VariableCollection),
        ('forced_variables', 'cardinality', '0.1'),
        ('forced_variables', 'type', data.VariableCollection),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('implementation_overview', 'cardinality', '1.1'),
        ('implementation_overview', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('prognostic_variables', 'cardinality', '0.1'),
        ('prognostic_variables', 'type', data.VariableCollection),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
    ),

    science.ConservationProperties: (
        ('corrected_conserved_prognostic_variables', 'cardinality', '0.1'),
        ('corrected_conserved_prognostic_variables', 'type', data.VariableCollection),
        ('correction_methodology', 'cardinality', '0.1'),
        ('correction_methodology', 'type', unicode),
        ('flux_correction_was_used', 'cardinality', '1.1'),
        ('flux_correction_was_used', 'type', bool),
    ),

    science.Detail: (
        ('content', 'cardinality', '0.1'),
        ('content', 'type', unicode),
        ('context', 'cardinality', '1.1'),
        ('context', 'type', unicode),
        ('detail_selection', 'cardinality', '0.N'),
        ('detail_selection', 'type', unicode),
        ('from_vocab', 'cardinality', '0.1'),
        ('from_vocab', 'type', unicode),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('select', 'cardinality', '0.1'),
        ('select', 'type', unicode),
        ('with_cardinality', 'cardinality', '0.1'),
        ('with_cardinality', 'type', unicode),
    ),

    science.Extent: (
        ('bottom_vertical_level', 'cardinality', '0.1'),
        ('bottom_vertical_level', 'type', float),
        ('eastern_boundary', 'cardinality', '0.1'),
        ('eastern_boundary', 'type', float),
        ('is_global', 'cardinality', '1.1'),
        ('is_global', 'type', bool),
        ('northern_boundary', 'cardinality', '0.1'),
        ('northern_boundary', 'type', float),
        ('region_known_as', 'cardinality', '0.N'),
        ('region_known_as', 'type', unicode),
        ('southern_boundary', 'cardinality', '0.1'),
        ('southern_boundary', 'type', float),
        ('top_vertical_level', 'cardinality', '0.1'),
        ('top_vertical_level', 'type', float),
        ('western_boundary', 'cardinality', '0.1'),
        ('western_boundary', 'type', float),
        ('z_units', 'cardinality', '1.1'),
        ('z_units', 'type', unicode),
    ),

    science.Grid: (
        ('additional_details', 'cardinality', '0.N'),
        ('additional_details', 'type', science.Detail),
        ('grid_extent', 'cardinality', '0.1'),
        ('grid_extent', 'type', science.Extent),
        ('horizontal_grid_layout', 'cardinality', '0.1'),
        ('horizontal_grid_layout', 'type', unicode),
        ('horizontal_grid_type', 'cardinality', '0.1'),
        ('horizontal_grid_type', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('vertical_grid_layout', 'cardinality', '0.1'),
        ('vertical_grid_layout', 'type', unicode),
        ('vertical_grid_type', 'cardinality', '0.1'),
        ('vertical_grid_type', 'type', unicode),
    ),

    science.KeyProperties: (
        ('additional_detail', 'cardinality', '0.N'),
        ('additional_detail', 'type', science.Detail),
        ('extra_conservation_properties', 'cardinality', '0.1'),
        ('extra_conservation_properties', 'type', science.ConservationProperties),
        ('grid', 'cardinality', '1.1'),
        ('grid', 'type', science.Grid),
        ('resolution', 'cardinality', '1.1'),
        ('resolution', 'type', science.Resolution),
        ('time_step', 'cardinality', '1.1'),
        ('time_step', 'type', float),
        ('tuning_applied', 'cardinality', '0.1'),
        ('tuning_applied', 'type', science.Tuning),
    ),

    science.Model: (
        ('category', 'cardinality', '1.1'),
        ('category', 'type', unicode),
        ('coupled_components', 'cardinality', '0.N'),
        ('coupled_components', 'type', science.Model),
        ('coupler', 'cardinality', '0.1'),
        ('coupler', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('development_history', 'cardinality', '0.1'),
        ('development_history', 'type', software.DevelopmentPath),
        ('documentation', 'cardinality', '0.N'),
        ('documentation', 'type', shared.Reference),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('internal_software_components', 'cardinality', '0.N'),
        ('internal_software_components', 'type', software.SoftwareComponent),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('model_default_properties', 'cardinality', '0.1'),
        ('model_default_properties', 'type', science.KeyProperties),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('repository', 'cardinality', '0.1'),
        ('repository', 'type', shared.OnlineResource),
        ('simulates', 'cardinality', '0.N'),
        ('simulates', 'type', science.ScientificDomain),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    science.Process: (
        ('algorithms', 'cardinality', '0.N'),
        ('algorithms', 'type', science.Algorithm),
        ('context', 'cardinality', '1.1'),
        ('context', 'type', unicode),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('implementation_overview', 'cardinality', '1.1'),
        ('implementation_overview', 'type', unicode),
        ('keywords', 'cardinality', '0.1'),
        ('keywords', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', science.Detail),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('sub_processes', 'cardinality', '0.N'),
        ('sub_processes', 'type', science.SubProcess),
    ),

    science.Resolution: (
        ('equivalent_resolution_km', 'cardinality', '0.1'),
        ('equivalent_resolution_km', 'type', float),
        ('is_adaptive_grid', 'cardinality', '0.1'),
        ('is_adaptive_grid', 'type', bool),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('number_of_levels', 'cardinality', '0.1'),
        ('number_of_levels', 'type', int),
        ('number_of_xy_gridpoints', 'cardinality', '0.1'),
        ('number_of_xy_gridpoints', 'type', int),
        ('typical_x_degrees', 'cardinality', '0.1'),
        ('typical_x_degrees', 'type', float),
        ('typical_y_degrees', 'cardinality', '0.1'),
        ('typical_y_degrees', 'type', float),
    ),

    science.ScienceContext: (
        ('context', 'cardinality', '1.1'),
        ('context', 'type', unicode),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
    ),

    science.ScientificDomain: (
        ('differing_key_properties', 'cardinality', '0.1'),
        ('differing_key_properties', 'type', science.KeyProperties),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('overview', 'cardinality', '0.1'),
        ('overview', 'type', unicode),
        ('realm', 'cardinality', '0.1'),
        ('realm', 'type', unicode),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
        ('simulates', 'cardinality', '1.N'),
        ('simulates', 'type', science.Process),
    ),

    science.SubProcess: (
        ('context', 'cardinality', '1.1'),
        ('context', 'type', unicode),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('implementation_overview', 'cardinality', '1.1'),
        ('implementation_overview', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', science.Detail),
        ('references', 'cardinality', '0.N'),
        ('references', 'type', shared.Reference),
    ),

    science.Tuning: (
        ('description', 'cardinality', '1.1'),
        ('description', 'type', unicode),
        ('global_mean_metrics_used', 'cardinality', '0.1'),
        ('global_mean_metrics_used', 'type', data.VariableCollection),
        ('regional_metrics_used', 'cardinality', '0.1'),
        ('regional_metrics_used', 'type', data.VariableCollection),
        ('trend_metrics_used', 'cardinality', '0.1'),
        ('trend_metrics_used', 'type', data.VariableCollection),
    ),

    shared.Calendar: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('month_lengths', 'cardinality', '0.N'),
        ('month_lengths', 'type', int),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('standard_name', 'cardinality', '1.1'),
        ('standard_name', 'type', unicode),
    ),

    shared.Cimtext: (
        ('content', 'cardinality', '1.1'),
        ('content', 'type', unicode),
        ('content_type', 'cardinality', '1.1'),
        ('content_type', 'type', unicode),
    ),

    shared.DateTime: (
        ('offset', 'cardinality', '0.1'),
        ('offset', 'type', bool),
        ('value', 'cardinality', '1.1'),
        ('value', 'type', unicode),
    ),

    shared.DatetimeSet: (
        ('length', 'cardinality', '1.1'),
        ('length', 'type', int),
    ),

    shared.DocMetaInfo: (
        ('author', 'cardinality', '0.1'),
        ('author', 'type', shared.Party),
        ('create_date', 'cardinality', '1.1'),
        ('create_date', 'type', datetime.datetime),
        ('drs_keys', 'cardinality', '0.N'),
        ('drs_keys', 'type', unicode),
        ('drs_path', 'cardinality', '0.1'),
        ('drs_path', 'type', unicode),
        ('external_ids', 'cardinality', '0.N'),
        ('external_ids', 'type', unicode),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('institute', 'cardinality', '0.1'),
        ('institute', 'type', unicode),
        ('language', 'cardinality', '1.1'),
        ('language', 'type', unicode),
        ('project', 'cardinality', '1.1'),
        ('project', 'type', unicode),
        ('sort_key', 'cardinality', '0.1'),
        ('sort_key', 'type', unicode),
        ('source', 'cardinality', '1.1'),
        ('source', 'type', unicode),
        ('source_key', 'cardinality', '0.1'),
        ('source_key', 'type', unicode),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
        ('type_display_name', 'cardinality', '0.1'),
        ('type_display_name', 'type', unicode),
        ('type_sort_key', 'cardinality', '0.1'),
        ('type_sort_key', 'type', unicode),
        ('update_date', 'cardinality', '1.1'),
        ('update_date', 'type', datetime.datetime),
        ('version', 'cardinality', '1.1'),
        ('version', 'type', int),
    ),

    shared.DocReference: (
        ('constraint_vocabulary', 'cardinality', '0.1'),
        ('constraint_vocabulary', 'type', unicode),
        ('context', 'cardinality', '0.1'),
        ('context', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('linkage', 'cardinality', '1.1'),
        ('linkage', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('protocol', 'cardinality', '0.1'),
        ('protocol', 'type', unicode),
        ('relationship', 'cardinality', '0.1'),
        ('relationship', 'type', unicode),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', int),
    ),

    shared.ExternalDocument: (
        ('authorship', 'cardinality', '0.1'),
        ('authorship', 'type', unicode),
        ('date', 'cardinality', '0.1'),
        ('date', 'type', unicode),
        ('doi', 'cardinality', '0.1'),
        ('doi', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('online_at', 'cardinality', '0.1'),
        ('online_at', 'type', shared.OnlineResource),
        ('publication_detail', 'cardinality', '0.1'),
        ('publication_detail', 'type', unicode),
        ('title', 'cardinality', '1.1'),
        ('title', 'type', unicode),
    ),

    shared.IrregularDateset: (
        ('date_set', 'cardinality', '1.1'),
        ('date_set', 'type', unicode),
        ('length', 'cardinality', '1.1'),
        ('length', 'type', int),
    ),

    shared.KeyFloat: (
        ('key', 'cardinality', '1.1'),
        ('key', 'type', unicode),
        ('value', 'cardinality', '1.1'),
        ('value', 'type', float),
    ),

    shared.NumberArray: (
        ('values', 'cardinality', '1.1'),
        ('values', 'type', unicode),
    ),

    shared.OnlineResource: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('linkage', 'cardinality', '1.1'),
        ('linkage', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('protocol', 'cardinality', '0.1'),
        ('protocol', 'type', unicode),
    ),

    shared.Party: (
        ('address', 'cardinality', '0.1'),
        ('address', 'type', unicode),
        ('email', 'cardinality', '0.1'),
        ('email', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('orcid_id', 'cardinality', '0.1'),
        ('orcid_id', 'type', unicode),
        ('organisation', 'cardinality', '0.1'),
        ('organisation', 'type', bool),
        ('url', 'cardinality', '0.1'),
        ('url', 'type', shared.OnlineResource),
    ),

    shared.Pid: (
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('resolution_service', 'cardinality', '1.1'),
        ('resolution_service', 'type', shared.OnlineResource),
    ),

    shared.QualityReview: (
        ('date', 'cardinality', '1.1'),
        ('date', 'type', unicode),
        ('metadata_reviewer', 'cardinality', '1.1'),
        ('metadata_reviewer', 'type', shared.Party),
        ('quality_description', 'cardinality', '1.1'),
        ('quality_description', 'type', unicode),
        ('quality_status', 'cardinality', '0.1'),
        ('quality_status', 'type', unicode),
    ),

    shared.Reference: (
        ('context', 'cardinality', '0.1'),
        ('context', 'type', unicode),
        ('document', 'cardinality', '1.1'),
        ('document', 'type', shared.ExternalDocument),
    ),

    shared.RegularTimeset: (
        ('increment', 'cardinality', '1.1'),
        ('increment', 'type', shared.TimePeriod),
        ('length', 'cardinality', '1.1'),
        ('length', 'type', int),
        ('start_date', 'cardinality', '1.1'),
        ('start_date', 'type', shared.DateTime),
    ),

    shared.Responsibility: (
        ('party', 'cardinality', '1.N'),
        ('party', 'type', shared.Party),
        ('role', 'cardinality', '1.1'),
        ('role', 'type', unicode),
        ('when', 'cardinality', '0.1'),
        ('when', 'type', shared.TimePeriod),
    ),

    shared.TimePeriod: (
        ('calendar', 'cardinality', '0.1'),
        ('calendar', 'type', shared.Calendar),
        ('date', 'cardinality', '0.1'),
        ('date', 'type', shared.DateTime),
        ('date_type', 'cardinality', '1.1'),
        ('date_type', 'type', unicode),
        ('length', 'cardinality', '1.1'),
        ('length', 'type', int),
        ('units', 'cardinality', '1.1'),
        ('units', 'type', unicode),
    ),

    shared.TimesliceList: (
        ('members', 'cardinality', '1.1'),
        ('members', 'type', shared.NumberArray),
        ('units', 'cardinality', '1.1'),
        ('units', 'type', unicode),
    ),

    software.ComponentBase: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('development_history', 'cardinality', '0.1'),
        ('development_history', 'type', software.DevelopmentPath),
        ('documentation', 'cardinality', '0.N'),
        ('documentation', 'type', shared.Reference),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('repository', 'cardinality', '0.1'),
        ('repository', 'type', shared.OnlineResource),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.Composition: (
        ('couplings', 'cardinality', '0.N'),
        ('couplings', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
    ),

    software.DevelopmentPath: (
        ('consortium_name', 'cardinality', '0.1'),
        ('consortium_name', 'type', unicode),
        ('creators', 'cardinality', '0.N'),
        ('creators', 'type', shared.Responsibility),
        ('developed_in_house', 'cardinality', '1.1'),
        ('developed_in_house', 'type', bool),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', shared.Responsibility),
        ('previous_version', 'cardinality', '0.1'),
        ('previous_version', 'type', unicode),
    ),

    software.EntryPoint: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
    ),

    software.Gridspec: (
        ('description', 'cardinality', '1.1'),
        ('description', 'type', unicode),
    ),

    software.SoftwareComponent: (
        ('composition', 'cardinality', '0.1'),
        ('composition', 'type', software.Composition),
        ('connection_points', 'cardinality', '0.N'),
        ('connection_points', 'type', software.Variable),
        ('coupling_framework', 'cardinality', '0.1'),
        ('coupling_framework', 'type', unicode),
        ('dependencies', 'cardinality', '0.N'),
        ('dependencies', 'type', software.EntryPoint),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('development_history', 'cardinality', '0.1'),
        ('development_history', 'type', software.DevelopmentPath),
        ('documentation', 'cardinality', '0.N'),
        ('documentation', 'type', shared.Reference),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', software.Gridspec),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', unicode),
        ('license', 'cardinality', '0.1'),
        ('license', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('repository', 'cardinality', '0.1'),
        ('repository', 'type', shared.OnlineResource),
        ('sub_components', 'cardinality', '0.N'),
        ('sub_components', 'type', software.SoftwareComponent),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.Variable: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('prognostic', 'cardinality', '1.1'),
        ('prognostic', 'type', bool),
    ),


}