# -*- coding: utf-8 -*-

"""
.. module:: cim.v1.constraints.py

   :license: GPL / CeCILL
   :platform: Unix, Windows
   :synopsis: The set of constraints over the cim.v1.

.. moduleauthor:: Earth System Documentation (ES-DOC) <dev@es-doc.org>
.. note:: Code generated using the esdoc-mp framework.

"""
import datetime
import uuid

import typeset_for_activity_package as activity
import typeset_for_data_package as data
import typeset_for_grids_package as grids
import typeset_for_misc_package as misc
import typeset_for_quality_package as quality
import typeset_for_shared_package as shared
import typeset_for_software_package as software



# Map of ontology types to type constraints.
CONSTRAINTS = {
    activity.Activity: (
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
    ),

    activity.BoundaryCondition: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
    ),

    activity.Conformance: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('frequency', 'cardinality', '0.1'),
        ('frequency', 'type', unicode),
        ('is_conformant', 'cardinality', '1.1'),
        ('is_conformant', 'type', bool),
        ('requirements', 'cardinality', '0.N'),
        ('requirements', 'type', activity.NumericalRequirement),
        ('sources', 'cardinality', '0.N'),
        ('sources', 'type', shared.DataSource),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    activity.DownscalingSimulation: (
        ('calendar', 'cardinality', '1.1'),
        ('calendar', 'type', shared.Calendar),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('downscaled_from', 'cardinality', '1.1'),
        ('downscaled_from', 'type', shared.DataSource),
        ('downscaling_id', 'cardinality', '0.1'),
        ('downscaling_id', 'type', unicode),
        ('downscaling_type', 'cardinality', '0.1'),
        ('downscaling_type', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('inputs', 'cardinality', '0.N'),
        ('inputs', 'type', software.Coupling),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('outputs', 'cardinality', '0.N'),
        ('outputs', 'type', data.DataObject),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.Ensemble: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('members', 'cardinality', '1.N'),
        ('members', 'type', activity.EnsembleMember),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('outputs', 'cardinality', '0.N'),
        ('outputs', 'type', shared.DataSource),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
        ('types', 'cardinality', '1.N'),
        ('types', 'type', unicode),
    ),

    activity.EnsembleMember: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('ensemble', 'cardinality', '0.1'),
        ('ensemble', 'type', activity.Ensemble),
        ('ensemble_ids', 'cardinality', '0.N'),
        ('ensemble_ids', 'type', shared.StandardName),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('simulation', 'cardinality', '0.1'),
        ('simulation', 'type', activity.Simulation),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.Experiment: (
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('generates', 'cardinality', '0.N'),
        ('generates', 'type', unicode),
        ('measurement_campaigns', 'cardinality', '0.N'),
        ('measurement_campaigns', 'type', activity.MeasurementCampaign),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('requires', 'cardinality', '0.N'),
        ('requires', 'type', activity.NumericalActivity),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', unicode),
    ),

    activity.ExperimentRelationship: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('direction', 'cardinality', '1.1'),
        ('direction', 'type', unicode),
        ('target', 'cardinality', '1.1'),
        ('target', 'type', activity.ExperimentRelationshipTarget),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
    ),

    activity.ExperimentRelationshipTarget: (
        ('numerical_experiment', 'cardinality', '0.1'),
        ('numerical_experiment', 'type', activity.NumericalExperiment),
    ),

    activity.InitialCondition: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
    ),

    activity.LateralBoundaryCondition: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
    ),

    activity.MeasurementCampaign: (
        ('duration', 'cardinality', '1.1'),
        ('duration', 'type', int),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
    ),

    activity.NumericalActivity: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.NumericalExperiment: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('experiment_id', 'cardinality', '0.1'),
        ('experiment_id', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('generates', 'cardinality', '0.N'),
        ('generates', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('measurement_campaigns', 'cardinality', '0.N'),
        ('measurement_campaigns', 'type', activity.MeasurementCampaign),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('requirements', 'cardinality', '0.N'),
        ('requirements', 'type', activity.NumericalRequirement),
        ('requires', 'cardinality', '0.N'),
        ('requires', 'type', activity.NumericalActivity),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', unicode),
    ),

    activity.NumericalRequirement: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
    ),

    activity.NumericalRequirementOption: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('relationship', 'cardinality', '0.1'),
        ('relationship', 'type', unicode),
        ('sub_options', 'cardinality', '0.N'),
        ('sub_options', 'type', activity.NumericalRequirementOption),
    ),

    activity.OutputRequirement: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
    ),

    activity.PhysicalModification: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('frequency', 'cardinality', '0.1'),
        ('frequency', 'type', unicode),
        ('is_conformant', 'cardinality', '1.1'),
        ('is_conformant', 'type', bool),
        ('requirements', 'cardinality', '0.N'),
        ('requirements', 'type', activity.NumericalRequirement),
        ('sources', 'cardinality', '0.N'),
        ('sources', 'type', shared.DataSource),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    activity.Simulation: (
        ('authors', 'cardinality', '0.1'),
        ('authors', 'type', unicode),
        ('calendar', 'cardinality', '1.1'),
        ('calendar', 'type', shared.Calendar),
        ('conformances', 'cardinality', '0.N'),
        ('conformances', 'type', activity.Conformance),
        ('control_simulation', 'cardinality', '0.1'),
        ('control_simulation', 'type', activity.Simulation),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('inputs', 'cardinality', '0.N'),
        ('inputs', 'type', software.Coupling),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('outputs', 'cardinality', '0.N'),
        ('outputs', 'type', data.DataObject),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('restarts', 'cardinality', '0.N'),
        ('restarts', 'type', data.DataObject),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('simulation_id', 'cardinality', '0.1'),
        ('simulation_id', 'type', unicode),
        ('spinup_date_range', 'cardinality', '0.1'),
        ('spinup_date_range', 'type', shared.ClosedDateRange),
        ('spinup_simulation', 'cardinality', '0.1'),
        ('spinup_simulation', 'type', activity.Simulation),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.SimulationComposite: (
        ('authors', 'cardinality', '0.1'),
        ('authors', 'type', unicode),
        ('calendar', 'cardinality', '1.1'),
        ('calendar', 'type', shared.Calendar),
        ('child', 'cardinality', '0.N'),
        ('child', 'type', activity.Simulation),
        ('conformances', 'cardinality', '0.N'),
        ('conformances', 'type', activity.Conformance),
        ('control_simulation', 'cardinality', '0.1'),
        ('control_simulation', 'type', activity.Simulation),
        ('date_range', 'cardinality', '1.1'),
        ('date_range', 'type', shared.DateRange),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('inputs', 'cardinality', '0.N'),
        ('inputs', 'type', software.Coupling),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('outputs', 'cardinality', '0.N'),
        ('outputs', 'type', data.DataObject),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rank', 'cardinality', '1.1'),
        ('rank', 'type', int),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('restarts', 'cardinality', '0.N'),
        ('restarts', 'type', data.DataObject),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('simulation_id', 'cardinality', '0.1'),
        ('simulation_id', 'type', unicode),
        ('spinup_date_range', 'cardinality', '0.1'),
        ('spinup_date_range', 'type', shared.ClosedDateRange),
        ('spinup_simulation', 'cardinality', '0.1'),
        ('spinup_simulation', 'type', activity.Simulation),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.SimulationRelationship: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('direction', 'cardinality', '1.1'),
        ('direction', 'type', unicode),
        ('target', 'cardinality', '1.1'),
        ('target', 'type', activity.SimulationRelationshipTarget),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
    ),

    activity.SimulationRelationshipTarget: (
        ('simulation', 'cardinality', '0.1'),
        ('simulation', 'type', shared.DocReference),
        ('target', 'cardinality', '0.1'),
        ('target', 'type', unicode),
    ),

    activity.SimulationRun: (
        ('authors', 'cardinality', '0.1'),
        ('authors', 'type', unicode),
        ('calendar', 'cardinality', '1.1'),
        ('calendar', 'type', shared.Calendar),
        ('conformances', 'cardinality', '0.N'),
        ('conformances', 'type', activity.Conformance),
        ('control_simulation', 'cardinality', '0.1'),
        ('control_simulation', 'type', activity.Simulation),
        ('date_range', 'cardinality', '1.1'),
        ('date_range', 'type', shared.DateRange),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('inputs', 'cardinality', '0.N'),
        ('inputs', 'type', software.Coupling),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('model', 'cardinality', '0.1'),
        ('model', 'type', software.ModelComponent),
        ('outputs', 'cardinality', '0.N'),
        ('outputs', 'type', data.DataObject),
        ('projects', 'cardinality', '0.N'),
        ('projects', 'type', unicode),
        ('rationales', 'cardinality', '0.N'),
        ('rationales', 'type', unicode),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('restarts', 'cardinality', '0.N'),
        ('restarts', 'type', data.DataObject),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('simulation_id', 'cardinality', '0.1'),
        ('simulation_id', 'type', unicode),
        ('spinup_date_range', 'cardinality', '0.1'),
        ('spinup_date_range', 'type', shared.ClosedDateRange),
        ('spinup_simulation', 'cardinality', '0.1'),
        ('spinup_simulation', 'type', activity.Simulation),
        ('supports', 'cardinality', '0.N'),
        ('supports', 'type', activity.Experiment),
    ),

    activity.SpatioTemporalConstraint: (
        ('date_range', 'cardinality', '0.1'),
        ('date_range', 'type', shared.DateRange),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.N'),
        ('options', 'type', activity.NumericalRequirementOption),
        ('requirement_type', 'cardinality', '1.1'),
        ('requirement_type', 'type', unicode),
        ('source', 'cardinality', '0.1'),
        ('source', 'type', shared.DataSource),
        ('spatial_resolution', 'cardinality', '0.1'),
        ('spatial_resolution', 'type', unicode),
    ),

    data.DataContent: (
        ('aggregation', 'cardinality', '0.1'),
        ('aggregation', 'type', unicode),
        ('frequency', 'cardinality', '0.1'),
        ('frequency', 'type', unicode),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('topic', 'cardinality', '1.1'),
        ('topic', 'type', data.DataTopic),
    ),

    data.DataDistribution: (
        ('access', 'cardinality', '0.1'),
        ('access', 'type', unicode),
        ('fee', 'cardinality', '0.1'),
        ('fee', 'type', unicode),
        ('format', 'cardinality', '0.1'),
        ('format', 'type', unicode),
        ('responsible_party', 'cardinality', '0.1'),
        ('responsible_party', 'type', shared.ResponsibleParty),
    ),

    data.DataExtent: (
        ('geographical', 'cardinality', '1.1'),
        ('geographical', 'type', data.DataExtentGeographical),
        ('temporal', 'cardinality', '1.1'),
        ('temporal', 'type', data.DataExtentTemporal),
    ),

    data.DataExtentGeographical: (
        ('east', 'cardinality', '0.1'),
        ('east', 'type', float),
        ('north', 'cardinality', '0.1'),
        ('north', 'type', float),
        ('south', 'cardinality', '0.1'),
        ('south', 'type', float),
        ('west', 'cardinality', '0.1'),
        ('west', 'type', float),
    ),

    data.DataExtentTemporal: (
        ('begin', 'cardinality', '0.1'),
        ('begin', 'type', datetime.date),
        ('end', 'cardinality', '0.1'),
        ('end', 'type', datetime.date),
        ('time_interval', 'cardinality', '0.1'),
        ('time_interval', 'type', data.DataExtentTimeInterval),
    ),

    data.DataExtentTimeInterval: (
        ('factor', 'cardinality', '0.1'),
        ('factor', 'type', int),
        ('radix', 'cardinality', '0.1'),
        ('radix', 'type', int),
        ('unit', 'cardinality', '0.1'),
        ('unit', 'type', unicode),
    ),

    data.DataHierarchyLevel: (
        ('is_open', 'cardinality', '0.1'),
        ('is_open', 'type', bool),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    data.DataObject: (
        ('acronym', 'cardinality', '0.1'),
        ('acronym', 'type', unicode),
        ('child_object', 'cardinality', '0.N'),
        ('child_object', 'type', data.DataObject),
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('content', 'cardinality', '0.N'),
        ('content', 'type', data.DataContent),
        ('data_status', 'cardinality', '0.1'),
        ('data_status', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('distribution', 'cardinality', '0.1'),
        ('distribution', 'type', data.DataDistribution),
        ('extent', 'cardinality', '0.1'),
        ('extent', 'type', data.DataExtent),
        ('geometry_model', 'cardinality', '0.1'),
        ('geometry_model', 'type', unicode),
        ('hierarchy_level', 'cardinality', '0.1'),
        ('hierarchy_level', 'type', data.DataHierarchyLevel),
        ('keyword', 'cardinality', '0.1'),
        ('keyword', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('parent_object', 'cardinality', '0.1'),
        ('parent_object', 'type', data.DataObject),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', data.DataProperty),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('restriction', 'cardinality', '0.N'),
        ('restriction', 'type', data.DataRestriction),
        ('source_simulation', 'cardinality', '0.1'),
        ('source_simulation', 'type', unicode),
        ('storage', 'cardinality', '0.N'),
        ('storage', 'type', data.DataStorage),
    ),

    data.DataProperty: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    data.DataRestriction: (
        ('license', 'cardinality', '0.1'),
        ('license', 'type', shared.License),
        ('restriction', 'cardinality', '0.1'),
        ('restriction', 'type', unicode),
        ('scope', 'cardinality', '0.1'),
        ('scope', 'type', unicode),
    ),

    data.DataStorage: (
        ('format', 'cardinality', '0.1'),
        ('format', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('modification_date', 'cardinality', '0.1'),
        ('modification_date', 'type', datetime.datetime),
        ('size', 'cardinality', '0.1'),
        ('size', 'type', int),
    ),

    data.DataStorageDb: (
        ('access_string', 'cardinality', '0.1'),
        ('access_string', 'type', unicode),
        ('format', 'cardinality', '0.1'),
        ('format', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('modification_date', 'cardinality', '0.1'),
        ('modification_date', 'type', datetime.datetime),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('owner', 'cardinality', '0.1'),
        ('owner', 'type', unicode),
        ('size', 'cardinality', '0.1'),
        ('size', 'type', int),
        ('table', 'cardinality', '0.1'),
        ('table', 'type', unicode),
    ),

    data.DataStorageFile: (
        ('file_name', 'cardinality', '0.1'),
        ('file_name', 'type', unicode),
        ('file_system', 'cardinality', '0.1'),
        ('file_system', 'type', unicode),
        ('format', 'cardinality', '0.1'),
        ('format', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('modification_date', 'cardinality', '0.1'),
        ('modification_date', 'type', datetime.datetime),
        ('path', 'cardinality', '0.1'),
        ('path', 'type', unicode),
        ('size', 'cardinality', '0.1'),
        ('size', 'type', int),
    ),

    data.DataStorageIp: (
        ('file_name', 'cardinality', '0.1'),
        ('file_name', 'type', unicode),
        ('format', 'cardinality', '0.1'),
        ('format', 'type', unicode),
        ('host', 'cardinality', '0.1'),
        ('host', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('modification_date', 'cardinality', '0.1'),
        ('modification_date', 'type', datetime.datetime),
        ('path', 'cardinality', '0.1'),
        ('path', 'type', unicode),
        ('protocol', 'cardinality', '0.1'),
        ('protocol', 'type', unicode),
        ('size', 'cardinality', '0.1'),
        ('size', 'type', int),
    ),

    data.DataTopic: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('unit', 'cardinality', '0.1'),
        ('unit', 'type', unicode),
    ),

    grids.CoordinateList: (
        ('has_constant_offset', 'cardinality', '0.1'),
        ('has_constant_offset', 'type', bool),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('uom', 'cardinality', '0.1'),
        ('uom', 'type', unicode),
    ),

    grids.GridExtent: (
        ('maximum_latitude', 'cardinality', '1.1'),
        ('maximum_latitude', 'type', unicode),
        ('maximum_longitude', 'cardinality', '1.1'),
        ('maximum_longitude', 'type', unicode),
        ('minimum_latitude', 'cardinality', '1.1'),
        ('minimum_latitude', 'type', unicode),
        ('minimum_longitude', 'cardinality', '1.1'),
        ('minimum_longitude', 'type', unicode),
        ('units', 'cardinality', '0.1'),
        ('units', 'type', unicode),
    ),

    grids.GridMosaic: (
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('extent', 'cardinality', '0.1'),
        ('extent', 'type', grids.GridExtent),
        ('has_congruent_tiles', 'cardinality', '0.1'),
        ('has_congruent_tiles', 'type', bool),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', unicode),
        ('is_leaf', 'cardinality', '1.1'),
        ('is_leaf', 'type', bool),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('mnemonic', 'cardinality', '0.1'),
        ('mnemonic', 'type', unicode),
        ('mosaic_count', 'cardinality', '0.1'),
        ('mosaic_count', 'type', int),
        ('mosaics', 'cardinality', '0.N'),
        ('mosaics', 'type', grids.GridMosaic),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('tile_count', 'cardinality', '0.1'),
        ('tile_count', 'type', int),
        ('tiles', 'cardinality', '0.N'),
        ('tiles', 'type', grids.GridTile),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
    ),

    grids.GridProperty: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    grids.GridSpec: (
        ('esm_exchange_grids', 'cardinality', '0.N'),
        ('esm_exchange_grids', 'type', grids.GridMosaic),
        ('esm_model_grids', 'cardinality', '0.N'),
        ('esm_model_grids', 'type', grids.GridMosaic),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
    ),

    grids.GridTile: (
        ('area', 'cardinality', '0.1'),
        ('area', 'type', unicode),
        ('cell_array', 'cardinality', '0.1'),
        ('cell_array', 'type', unicode),
        ('cell_ref_array', 'cardinality', '0.1'),
        ('cell_ref_array', 'type', unicode),
        ('coord_file', 'cardinality', '0.1'),
        ('coord_file', 'type', unicode),
        ('coordinate_pole', 'cardinality', '0.1'),
        ('coordinate_pole', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('discretization_type', 'cardinality', '0.1'),
        ('discretization_type', 'type', unicode),
        ('extent', 'cardinality', '0.1'),
        ('extent', 'type', grids.GridExtent),
        ('geometry_type', 'cardinality', '0.1'),
        ('geometry_type', 'type', unicode),
        ('grid_north_pole', 'cardinality', '0.1'),
        ('grid_north_pole', 'type', unicode),
        ('horizontal_crs', 'cardinality', '0.1'),
        ('horizontal_crs', 'type', unicode),
        ('horizontal_resolution', 'cardinality', '0.1'),
        ('horizontal_resolution', 'type', grids.GridTileResolutionType),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('is_conformal', 'cardinality', '0.1'),
        ('is_conformal', 'type', bool),
        ('is_regular', 'cardinality', '0.1'),
        ('is_regular', 'type', bool),
        ('is_terrain_following', 'cardinality', '0.1'),
        ('is_terrain_following', 'type', bool),
        ('is_uniform', 'cardinality', '0.1'),
        ('is_uniform', 'type', bool),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('mnemonic', 'cardinality', '0.1'),
        ('mnemonic', 'type', unicode),
        ('nx', 'cardinality', '0.1'),
        ('nx', 'type', int),
        ('ny', 'cardinality', '0.1'),
        ('ny', 'type', int),
        ('nz', 'cardinality', '0.1'),
        ('nz', 'type', int),
        ('refinement_scheme', 'cardinality', '0.1'),
        ('refinement_scheme', 'type', unicode),
        ('short_name', 'cardinality', '0.1'),
        ('short_name', 'type', unicode),
        ('simple_grid_geom', 'cardinality', '0.1'),
        ('simple_grid_geom', 'type', grids.SimpleGridGeometry),
        ('vertical_crs', 'cardinality', '0.1'),
        ('vertical_crs', 'type', unicode),
        ('vertical_resolution', 'cardinality', '0.1'),
        ('vertical_resolution', 'type', grids.GridTileResolutionType),
        ('zcoords', 'cardinality', '0.1'),
        ('zcoords', 'type', grids.VerticalCoordinateList),
    ),

    grids.GridTileResolutionType: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', grids.GridProperty),
    ),

    grids.SimpleGridGeometry: (
        ('dim_order', 'cardinality', '0.1'),
        ('dim_order', 'type', unicode),
        ('is_mesh', 'cardinality', '0.1'),
        ('is_mesh', 'type', bool),
        ('num_dims', 'cardinality', '1.1'),
        ('num_dims', 'type', int),
        ('xcoords', 'cardinality', '1.1'),
        ('xcoords', 'type', grids.CoordinateList),
        ('ycoords', 'cardinality', '1.1'),
        ('ycoords', 'type', grids.CoordinateList),
        ('zcoords', 'cardinality', '0.1'),
        ('zcoords', 'type', grids.CoordinateList),
    ),

    grids.VerticalCoordinateList: (
        ('form', 'cardinality', '0.1'),
        ('form', 'type', unicode),
        ('has_constant_offset', 'cardinality', '0.1'),
        ('has_constant_offset', 'type', bool),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', grids.GridProperty),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('uom', 'cardinality', '0.1'),
        ('uom', 'type', unicode),
    ),

    misc.DocumentSet: (
        ('data', 'cardinality', '0.N'),
        ('data', 'type', data.DataObject),
        ('ensembles', 'cardinality', '0.N'),
        ('ensembles', 'type', activity.Ensemble),
        ('experiment', 'cardinality', '0.1'),
        ('experiment', 'type', activity.NumericalExperiment),
        ('grids', 'cardinality', '0.N'),
        ('grids', 'type', grids.GridSpec),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('model', 'cardinality', '0.1'),
        ('model', 'type', software.ModelComponent),
        ('platform', 'cardinality', '0.1'),
        ('platform', 'type', shared.Platform),
        ('simulation', 'cardinality', '0.1'),
        ('simulation', 'type', activity.SimulationRun),
    ),

    quality.CimQuality: (
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('reports', 'cardinality', '0.N'),
        ('reports', 'type', quality.Report),
    ),

    quality.Evaluation: (
        ('date', 'cardinality', '0.1'),
        ('date', 'type', datetime.datetime),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('did_pass', 'cardinality', '0.1'),
        ('did_pass', 'type', bool),
        ('explanation', 'cardinality', '0.1'),
        ('explanation', 'type', unicode),
        ('specification', 'cardinality', '0.1'),
        ('specification', 'type', unicode),
        ('specification_hyperlink', 'cardinality', '0.1'),
        ('specification_hyperlink', 'type', unicode),
        ('title', 'cardinality', '0.1'),
        ('title', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('type_hyperlink', 'cardinality', '0.1'),
        ('type_hyperlink', 'type', unicode),
    ),

    quality.Measure: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('identification', 'cardinality', '0.1'),
        ('identification', 'type', unicode),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
    ),

    quality.Report: (
        ('date', 'cardinality', '0.1'),
        ('date', 'type', datetime.datetime),
        ('evaluation', 'cardinality', '1.1'),
        ('evaluation', 'type', quality.Evaluation),
        ('evaluator', 'cardinality', '0.1'),
        ('evaluator', 'type', shared.ResponsibleParty),
        ('measure', 'cardinality', '1.1'),
        ('measure', 'type', quality.Measure),
    ),

    shared.Calendar: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('range', 'cardinality', '0.1'),
        ('range', 'type', shared.DateRange),
    ),

    shared.Change: (
        ('author', 'cardinality', '0.1'),
        ('author', 'type', shared.ResponsibleParty),
        ('date', 'cardinality', '0.1'),
        ('date', 'type', datetime.datetime),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('details', 'cardinality', '1.N'),
        ('details', 'type', shared.ChangeProperty),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    shared.ChangeProperty: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', unicode),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    shared.Citation: (
        ('alternative_title', 'cardinality', '0.1'),
        ('alternative_title', 'type', unicode),
        ('collective_title', 'cardinality', '0.1'),
        ('collective_title', 'type', unicode),
        ('date', 'cardinality', '0.1'),
        ('date', 'type', datetime.datetime),
        ('date_type', 'cardinality', '0.1'),
        ('date_type', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('organisation', 'cardinality', '0.1'),
        ('organisation', 'type', unicode),
        ('role', 'cardinality', '0.1'),
        ('role', 'type', unicode),
        ('title', 'cardinality', '0.1'),
        ('title', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    shared.ClosedDateRange: (
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', unicode),
        ('end', 'cardinality', '0.1'),
        ('end', 'type', datetime.datetime),
        ('start', 'cardinality', '1.1'),
        ('start', 'type', datetime.datetime),
    ),

    shared.Compiler: (
        ('environment_variables', 'cardinality', '0.1'),
        ('environment_variables', 'type', unicode),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('options', 'cardinality', '0.1'),
        ('options', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('version', 'cardinality', '1.1'),
        ('version', 'type', unicode),
    ),

    shared.Daily360: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('range', 'cardinality', '0.1'),
        ('range', 'type', shared.DateRange),
    ),

    shared.DataSource: (
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
    ),

    shared.DateRange: (
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', unicode),
    ),

    shared.DocGenealogy: (
        ('relationships', 'cardinality', '0.N'),
        ('relationships', 'type', shared.DocRelationship),
    ),

    shared.DocMetaInfo: (
        ('author', 'cardinality', '0.1'),
        ('author', 'type', shared.ResponsibleParty),
        ('create_date', 'cardinality', '1.1'),
        ('create_date', 'type', datetime.datetime),
        ('drs_keys', 'cardinality', '0.N'),
        ('drs_keys', 'type', unicode),
        ('drs_path', 'cardinality', '0.1'),
        ('drs_path', 'type', unicode),
        ('external_ids', 'cardinality', '0.N'),
        ('external_ids', 'type', shared.StandardName),
        ('genealogy', 'cardinality', '0.1'),
        ('genealogy', 'type', shared.DocGenealogy),
        ('id', 'cardinality', '1.1'),
        ('id', 'type', uuid.UUID),
        ('institute', 'cardinality', '0.1'),
        ('institute', 'type', unicode),
        ('language', 'cardinality', '1.1'),
        ('language', 'type', unicode),
        ('project', 'cardinality', '1.1'),
        ('project', 'type', unicode),
        ('sort_key', 'cardinality', '0.1'),
        ('sort_key', 'type', unicode),
        ('source', 'cardinality', '1.1'),
        ('source', 'type', unicode),
        ('source_key', 'cardinality', '0.1'),
        ('source_key', 'type', unicode),
        ('status', 'cardinality', '0.1'),
        ('status', 'type', unicode),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
        ('type_display_name', 'cardinality', '0.1'),
        ('type_display_name', 'type', unicode),
        ('type_sort_key', 'cardinality', '0.1'),
        ('type_sort_key', 'type', unicode),
        ('update_date', 'cardinality', '1.1'),
        ('update_date', 'type', datetime.datetime),
        ('version', 'cardinality', '1.1'),
        ('version', 'type', int),
    ),

    shared.DocReference: (
        ('changes', 'cardinality', '0.N'),
        ('changes', 'type', shared.Change),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('external_id', 'cardinality', '0.1'),
        ('external_id', 'type', unicode),
        ('id', 'cardinality', '0.1'),
        ('id', 'type', uuid.UUID),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('url', 'cardinality', '0.1'),
        ('url', 'type', unicode),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', int),
    ),

    shared.DocRelationship: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('direction', 'cardinality', '1.1'),
        ('direction', 'type', unicode),
        ('target', 'cardinality', '1.1'),
        ('target', 'type', shared.DocRelationshipTarget),
        ('type', 'cardinality', '1.1'),
        ('type', 'type', unicode),
    ),

    shared.DocRelationshipTarget: (
        ('reference', 'cardinality', '0.1'),
        ('reference', 'type', shared.DocReference),
    ),

    shared.License: (
        ('contact', 'cardinality', '0.1'),
        ('contact', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('is_unrestricted', 'cardinality', '0.1'),
        ('is_unrestricted', 'type', bool),
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
    ),

    shared.Machine: (
        ('cores_per_processor', 'cardinality', '0.1'),
        ('cores_per_processor', 'type', int),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('interconnect', 'cardinality', '0.1'),
        ('interconnect', 'type', unicode),
        ('libraries', 'cardinality', '0.N'),
        ('libraries', 'type', unicode),
        ('location', 'cardinality', '0.1'),
        ('location', 'type', unicode),
        ('maximum_processors', 'cardinality', '0.1'),
        ('maximum_processors', 'type', int),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('operating_system', 'cardinality', '0.1'),
        ('operating_system', 'type', unicode),
        ('processor_type', 'cardinality', '0.1'),
        ('processor_type', 'type', unicode),
        ('system', 'cardinality', '0.1'),
        ('system', 'type', unicode),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('vendor', 'cardinality', '0.1'),
        ('vendor', 'type', unicode),
    ),

    shared.MachineCompilerUnit: (
        ('compilers', 'cardinality', '0.N'),
        ('compilers', 'type', shared.Compiler),
        ('machine', 'cardinality', '1.1'),
        ('machine', 'type', shared.Machine),
    ),

    shared.OpenDateRange: (
        ('duration', 'cardinality', '0.1'),
        ('duration', 'type', unicode),
        ('end', 'cardinality', '0.1'),
        ('end', 'type', datetime.datetime),
        ('start', 'cardinality', '0.1'),
        ('start', 'type', datetime.datetime),
    ),

    shared.PerpetualPeriod: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('range', 'cardinality', '0.1'),
        ('range', 'type', shared.DateRange),
    ),

    shared.Platform: (
        ('contacts', 'cardinality', '0.N'),
        ('contacts', 'type', shared.ResponsibleParty),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('units', 'cardinality', '1.N'),
        ('units', 'type', shared.MachineCompilerUnit),
    ),

    shared.Property: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    shared.RealCalendar: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('length', 'cardinality', '0.1'),
        ('length', 'type', int),
        ('range', 'cardinality', '0.1'),
        ('range', 'type', shared.DateRange),
    ),

    shared.Relationship: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('direction', 'cardinality', '1.1'),
        ('direction', 'type', unicode),
    ),

    shared.ResponsibleParty: (
        ('abbreviation', 'cardinality', '0.1'),
        ('abbreviation', 'type', unicode),
        ('address', 'cardinality', '0.1'),
        ('address', 'type', unicode),
        ('email', 'cardinality', '0.1'),
        ('email', 'type', unicode),
        ('individual_name', 'cardinality', '0.1'),
        ('individual_name', 'type', unicode),
        ('organisation_name', 'cardinality', '0.1'),
        ('organisation_name', 'type', unicode),
        ('role', 'cardinality', '0.1'),
        ('role', 'type', unicode),
        ('url', 'cardinality', '0.1'),
        ('url', 'type', unicode),
    ),

    shared.Standard: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    shared.StandardName: (
        ('is_open', 'cardinality', '1.1'),
        ('is_open', 'type', bool),
        ('standards', 'cardinality', '0.N'),
        ('standards', 'type', shared.Standard),
        ('value', 'cardinality', '1.1'),
        ('value', 'type', unicode),
    ),

    software.Component: (
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('code_access', 'cardinality', '0.1'),
        ('code_access', 'type', unicode),
        ('composition', 'cardinality', '0.1'),
        ('composition', 'type', software.Composition),
        ('coupling_framework', 'cardinality', '0.1'),
        ('coupling_framework', 'type', unicode),
        ('dependencies', 'cardinality', '0.N'),
        ('dependencies', 'type', software.EntryPoint),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', grids.GridSpec),
        ('is_embedded', 'cardinality', '0.1'),
        ('is_embedded', 'type', bool),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', software.ComponentLanguage),
        ('license', 'cardinality', '0.1'),
        ('license', 'type', shared.License),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('online_resource', 'cardinality', '0.1'),
        ('online_resource', 'type', unicode),
        ('parent', 'cardinality', '0.1'),
        ('parent', 'type', software.Component),
        ('previous_version', 'cardinality', '0.1'),
        ('previous_version', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ComponentProperty),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('sub_components', 'cardinality', '0.N'),
        ('sub_components', 'type', software.Component),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.ComponentLanguage: (
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ComponentLanguageProperty),
    ),

    software.ComponentLanguageProperty: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    software.ComponentProperty: (
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', unicode),
        ('intent', 'cardinality', '0.1'),
        ('intent', 'type', unicode),
        ('is_represented', 'cardinality', '1.1'),
        ('is_represented', 'type', bool),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('standard_names', 'cardinality', '0.N'),
        ('standard_names', 'type', unicode),
        ('sub_properties', 'cardinality', '0.N'),
        ('sub_properties', 'type', software.ComponentProperty),
        ('units', 'cardinality', '0.1'),
        ('units', 'type', unicode),
        ('values', 'cardinality', '0.N'),
        ('values', 'type', unicode),
    ),

    software.Composition: (
        ('couplings', 'cardinality', '0.N'),
        ('couplings', 'type', unicode),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
    ),

    software.Connection: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('priming', 'cardinality', '0.1'),
        ('priming', 'type', shared.DataSource),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ConnectionProperty),
        ('sources', 'cardinality', '0.N'),
        ('sources', 'type', software.ConnectionEndpoint),
        ('spatial_regridding', 'cardinality', '0.N'),
        ('spatial_regridding', 'type', software.SpatialRegridding),
        ('target', 'cardinality', '0.1'),
        ('target', 'type', software.ConnectionEndpoint),
        ('time_lag', 'cardinality', '0.1'),
        ('time_lag', 'type', unicode),
        ('time_profile', 'cardinality', '0.1'),
        ('time_profile', 'type', software.Timing),
        ('time_transformation', 'cardinality', '0.1'),
        ('time_transformation', 'type', software.TimeTransformation),
        ('transformers', 'cardinality', '0.N'),
        ('transformers', 'type', software.ProcessorComponent),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    software.ConnectionEndpoint: (
        ('data_source', 'cardinality', '0.1'),
        ('data_source', 'type', shared.DataSource),
        ('instance_id', 'cardinality', '0.1'),
        ('instance_id', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ConnectionProperty),
    ),

    software.ConnectionProperty: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    software.Coupling: (
        ('connections', 'cardinality', '0.N'),
        ('connections', 'type', software.Connection),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('is_fully_specified', 'cardinality', '1.1'),
        ('is_fully_specified', 'type', bool),
        ('priming', 'cardinality', '0.1'),
        ('priming', 'type', shared.DataSource),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.CouplingProperty),
        ('purpose', 'cardinality', '1.1'),
        ('purpose', 'type', unicode),
        ('sources', 'cardinality', '1.N'),
        ('sources', 'type', software.CouplingEndpoint),
        ('spatial_regriddings', 'cardinality', '0.N'),
        ('spatial_regriddings', 'type', software.SpatialRegridding),
        ('target', 'cardinality', '1.1'),
        ('target', 'type', software.CouplingEndpoint),
        ('time_lag', 'cardinality', '0.1'),
        ('time_lag', 'type', software.TimeLag),
        ('time_profile', 'cardinality', '0.1'),
        ('time_profile', 'type', software.Timing),
        ('time_transformation', 'cardinality', '0.1'),
        ('time_transformation', 'type', software.TimeTransformation),
        ('transformers', 'cardinality', '0.N'),
        ('transformers', 'type', software.ProcessorComponent),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
    ),

    software.CouplingEndpoint: (
        ('data_source', 'cardinality', '0.1'),
        ('data_source', 'type', shared.DataSource),
        ('instance_id', 'cardinality', '0.1'),
        ('instance_id', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.CouplingProperty),
    ),

    software.CouplingProperty: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    software.Deployment: (
        ('deployment_date', 'cardinality', '0.1'),
        ('deployment_date', 'type', datetime.datetime),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('executable_arguments', 'cardinality', '0.N'),
        ('executable_arguments', 'type', unicode),
        ('executable_name', 'cardinality', '0.1'),
        ('executable_name', 'type', unicode),
        ('parallelisation', 'cardinality', '0.1'),
        ('parallelisation', 'type', software.Parallelisation),
        ('platform', 'cardinality', '0.1'),
        ('platform', 'type', shared.Platform),
    ),

    software.EntryPoint: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
    ),

    software.ModelComponent: (
        ('activity', 'cardinality', '0.1'),
        ('activity', 'type', activity.Activity),
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('code_access', 'cardinality', '0.1'),
        ('code_access', 'type', unicode),
        ('composition', 'cardinality', '0.1'),
        ('composition', 'type', software.Composition),
        ('coupling_framework', 'cardinality', '0.1'),
        ('coupling_framework', 'type', unicode),
        ('dependencies', 'cardinality', '0.N'),
        ('dependencies', 'type', software.EntryPoint),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', grids.GridSpec),
        ('is_embedded', 'cardinality', '0.1'),
        ('is_embedded', 'type', bool),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', software.ComponentLanguage),
        ('license', 'cardinality', '0.1'),
        ('license', 'type', shared.License),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('online_resource', 'cardinality', '0.1'),
        ('online_resource', 'type', unicode),
        ('parent', 'cardinality', '0.1'),
        ('parent', 'type', software.Component),
        ('previous_version', 'cardinality', '0.1'),
        ('previous_version', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ComponentProperty),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('sub_components', 'cardinality', '0.N'),
        ('sub_components', 'type', software.Component),
        ('timing', 'cardinality', '0.1'),
        ('timing', 'type', software.Timing),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('types', 'cardinality', '1.N'),
        ('types', 'type', unicode),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.Parallelisation: (
        ('processes', 'cardinality', '1.1'),
        ('processes', 'type', int),
        ('ranks', 'cardinality', '0.N'),
        ('ranks', 'type', software.Rank),
    ),

    software.ProcessorComponent: (
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('code_access', 'cardinality', '0.1'),
        ('code_access', 'type', unicode),
        ('composition', 'cardinality', '0.1'),
        ('composition', 'type', software.Composition),
        ('coupling_framework', 'cardinality', '0.1'),
        ('coupling_framework', 'type', unicode),
        ('dependencies', 'cardinality', '0.N'),
        ('dependencies', 'type', software.EntryPoint),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', grids.GridSpec),
        ('is_embedded', 'cardinality', '0.1'),
        ('is_embedded', 'type', bool),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', software.ComponentLanguage),
        ('license', 'cardinality', '0.1'),
        ('license', 'type', shared.License),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('online_resource', 'cardinality', '0.1'),
        ('online_resource', 'type', unicode),
        ('parent', 'cardinality', '0.1'),
        ('parent', 'type', software.Component),
        ('previous_version', 'cardinality', '0.1'),
        ('previous_version', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ComponentProperty),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('sub_components', 'cardinality', '0.N'),
        ('sub_components', 'type', software.Component),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.Rank: (
        ('increment', 'cardinality', '0.1'),
        ('increment', 'type', int),
        ('max', 'cardinality', '0.1'),
        ('max', 'type', int),
        ('min', 'cardinality', '0.1'),
        ('min', 'type', int),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', int),
    ),

    software.SpatialRegridding: (
        ('dimension', 'cardinality', '0.1'),
        ('dimension', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.SpatialRegriddingProperty),
        ('standard_method', 'cardinality', '0.1'),
        ('standard_method', 'type', unicode),
        ('user_method', 'cardinality', '0.1'),
        ('user_method', 'type', software.SpatialRegriddingUserMethod),
    ),

    software.SpatialRegriddingProperty: (
        ('name', 'cardinality', '0.1'),
        ('name', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', unicode),
    ),

    software.SpatialRegriddingUserMethod: (
        ('file', 'cardinality', '0.1'),
        ('file', 'type', data.DataObject),
        ('name', 'cardinality', '1.1'),
        ('name', 'type', unicode),
    ),

    software.StatisticalModelComponent: (
        ('citations', 'cardinality', '0.N'),
        ('citations', 'type', shared.Citation),
        ('code_access', 'cardinality', '0.1'),
        ('code_access', 'type', unicode),
        ('composition', 'cardinality', '0.1'),
        ('composition', 'type', software.Composition),
        ('coupling_framework', 'cardinality', '0.1'),
        ('coupling_framework', 'type', unicode),
        ('dependencies', 'cardinality', '0.N'),
        ('dependencies', 'type', software.EntryPoint),
        ('deployments', 'cardinality', '0.N'),
        ('deployments', 'type', software.Deployment),
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('funding_sources', 'cardinality', '0.N'),
        ('funding_sources', 'type', unicode),
        ('grid', 'cardinality', '0.1'),
        ('grid', 'type', grids.GridSpec),
        ('is_embedded', 'cardinality', '0.1'),
        ('is_embedded', 'type', bool),
        ('language', 'cardinality', '0.1'),
        ('language', 'type', software.ComponentLanguage),
        ('license', 'cardinality', '0.1'),
        ('license', 'type', shared.License),
        ('long_name', 'cardinality', '0.1'),
        ('long_name', 'type', unicode),
        ('meta', 'cardinality', '1.1'),
        ('meta', 'type', shared.DocMetaInfo),
        ('online_resource', 'cardinality', '0.1'),
        ('online_resource', 'type', unicode),
        ('parent', 'cardinality', '0.1'),
        ('parent', 'type', software.Component),
        ('previous_version', 'cardinality', '0.1'),
        ('previous_version', 'type', unicode),
        ('properties', 'cardinality', '0.N'),
        ('properties', 'type', software.ComponentProperty),
        ('purpose', 'cardinality', '0.1'),
        ('purpose', 'type', unicode),
        ('release_date', 'cardinality', '0.1'),
        ('release_date', 'type', datetime.datetime),
        ('responsible_parties', 'cardinality', '0.N'),
        ('responsible_parties', 'type', shared.ResponsibleParty),
        ('short_name', 'cardinality', '1.1'),
        ('short_name', 'type', unicode),
        ('sub_components', 'cardinality', '0.N'),
        ('sub_components', 'type', software.Component),
        ('timing', 'cardinality', '0.1'),
        ('timing', 'type', software.Timing),
        ('type', 'cardinality', '0.1'),
        ('type', 'type', unicode),
        ('types', 'cardinality', '1.N'),
        ('types', 'type', unicode),
        ('version', 'cardinality', '0.1'),
        ('version', 'type', unicode),
    ),

    software.TimeLag: (
        ('units', 'cardinality', '0.1'),
        ('units', 'type', unicode),
        ('value', 'cardinality', '0.1'),
        ('value', 'type', int),
    ),

    software.TimeTransformation: (
        ('description', 'cardinality', '0.1'),
        ('description', 'type', unicode),
        ('mapping_type', 'cardinality', '1.1'),
        ('mapping_type', 'type', unicode),
    ),

    software.Timing: (
        ('end', 'cardinality', '0.1'),
        ('end', 'type', datetime.datetime),
        ('is_variable_rate', 'cardinality', '0.1'),
        ('is_variable_rate', 'type', bool),
        ('rate', 'cardinality', '0.1'),
        ('rate', 'type', int),
        ('start', 'cardinality', '0.1'),
        ('start', 'type', datetime.datetime),
        ('units', 'cardinality', '0.1'),
        ('units', 'type', unicode),
    ),


}